
 import org.apache.spark.sql._
 import org.apache.spark.sql.types._
 
def get_file_structure(filename: String) : StructType = {

var struct: StructType = null
  
struct = filename  match {

//------------ZX00 

      case "ZX00" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
                StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("IDPAIE",StringType,true),
StructField("TYPAIE",StringType,true),
StructField("TYUSPA",StringType,true),
StructField("NUGEST",IntegerType,true),
StructField("NOMSAL",StringType,true),
StructField("TEMAJM",StringType,true),
StructField("TILOAD",DateType,true),
StructField("FLGNTG",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX0M 

                  case "ZX0M" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDCONT",StringType,true),
StructField("DATDEB",DateType,true),
StructField("CODLAN",StringType,true),
StructField("DATFIN",DateType,true),
StructField("TEMCON",StringType,true),
StructField("TYPCON",StringType,true),
StructField("MODTYC",StringType,true),
StructField("REPTYC",StringType,true),
StructField("LIBTYC",StringType,true),
StructField("NATCON",StringType,true),
StructField("MODNAC",StringType,true),
StructField("REPNAC",StringType,true),
StructField("LIBNAC",StringType,true),
StructField("DURANN",IntegerType,true),
StructField("DURMOI",IntegerType,true),
StructField("DURJOU",IntegerType,true),
StructField("DEBESS",DateType,true),
StructField("FINESS",DateType,true),
StructField("NBRPRO",IntegerType,true),
StructField("TITPOS",StringType,true),
StructField("TEMCAR",StringType,true),
StructField("QUALIF",StringType,true),
StructField("MODQUA",StringType,true),
StructField("REPQUA",StringType,true),
StructField("LIBQUA",StringType,true),
StructField("MODEMP",StringType,true),
StructField("REPEMP",StringType,true),
StructField("LIBEMP",StringType,true),
StructField("CLASSI",StringType,true),
StructField("MODCLA",StringType,true),
StructField("REPCLA",StringType,true),
StructField("LIBCLA",StringType,true),
StructField("TYPPAI",StringType,true),
StructField("MODTYP",StringType,true),
StructField("REPTYP",StringType,true),
StructField("LIBTYP",StringType,true),
StructField("MODTAR",StringType,true),
StructField("REPTAR",StringType,true),
StructField("LIBTAR",StringType,true),
StructField("POSITI",StringType,true),
StructField("MODPOS",StringType,true),
StructField("REPPOS",StringType,true),
StructField("LIBPOS",StringType,true),
StructField("INDICE",StringType,true),
StructField("MODIND",StringType,true),
StructField("REPIND",StringType,true),
StructField("LIBIND",StringType,true),
StructField("FILLE1",StringType,true),
StructField("COEFFI",StringType,true),
StructField("MODCOE",StringType,true),
StructField("REPCOE",StringType,true),
StructField("LIBCOE",StringType,true),
StructField("NIVEAU",StringType,true),
StructField("ECHELO",StringType,true),
StructField("FILLE2",StringType,true),
StructField("CONCOV",StringType,true),
StructField("MODCOC",StringType,true),
StructField("REPCOC",StringType,true),
StructField("LIBCOC",StringType,true),
StructField("TEMETA",StringType,true),
StructField("IDESTA",StringType,true),
StructField("MODETA",StringType,true),
StructField("REPETA",StringType,true),
StructField("LIBETA",StringType,true),
StructField("TEMHEU",StringType,true),
StructField("CODTRA",StringType,true),
StructField("MODTRA",StringType,true),
StructField("REPTRA",StringType,true),
StructField("LIBTRA",StringType,true),
StructField("CODINC",StringType,true),
StructField("MODINC",StringType,true),
StructField("REPINC",StringType,true),
StructField("LIBINC",StringType,true),
StructField("NBSTHD",IntegerType,true),
StructField("NBSTHW",IntegerType,true),
StructField("NBSTHM",IntegerType,true),
StructField("NBSTHP",IntegerType,true),
StructField("RTSTHR",IntegerType,true),
StructField("NBPDHD",IntegerType,true),
StructField("NBPDHW",IntegerType,true),
StructField("NBPDHM",IntegerType,true),
StructField("NBPDHP",IntegerType,true),
StructField("RTPDHR",IntegerType,true),
StructField("TEMSAL",StringType,true),
StructField("RUBAUG",StringType,true),
StructField("MODRUB",StringType,true),
StructField("REPRUB",StringType,true),
StructField("LIBRUB",StringType,true),
StructField("IDCUR",StringType,true),
StructField("IDCURX",StringType,true),
StructField("DUCMQF",StringType,true),
StructField("MODDUC",StringType,true),
StructField("REPDUC",StringType,true),
StructField("LIBDUC",StringType,true),
StructField("DUPAY0",StringType,true),
StructField("MODDUP",StringType,true),
StructField("REPDUP",StringType,true),
StructField("LIBDUP",StringType,true),
StructField("MTSAL",IntegerType,true),
StructField("CMOTIF",StringType,true),
StructField("MODCMO",StringType,true),
StructField("REPCMO",StringType,true),
StructField("LIBCMO",StringType,true),
StructField("AMHRL",IntegerType,true),
StructField("AMPYP",IntegerType,true),
StructField("MODHOR",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTC1M",StringType,true),
StructField("EXTC1C",StringType,true),
StructField("EXTC1R",StringType,true),
StructField("EXTC1L",StringType,true),
StructField("EXTC2M",StringType,true),
StructField("EXTC2C",StringType,true),
StructField("EXTC2R",StringType,true),
StructField("EXTC2L",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("CHBASE",StringType,true),
StructField("CHPERS",StringType,true),
StructField("CHSPEC",StringType,true),
StructField("CHNIVE",StringType,true),
StructField("CHECHL",StringType,true),
StructField("COGRPE",StringType,true),
StructField("CONIVE",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("FORANU",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX35 

                  case "ZX35" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("DATENT",DateType,true),
StructField("DATSOR",DateType,true),
StructField("PHYSOR",DateType,true),
StructField("MDCDEN",StringType,true),
StructField("CODENT",StringType,true),
StructField("REPENT",StringType,true),
StructField("LIBENT",StringType,true),
StructField("MDCDSO",StringType,true),
StructField("CODSOR",StringType,true),
StructField("REPSOR",StringType,true),
StructField("LIBSOR",StringType,true),
StructField("MDCGST",StringType,true),
StructField("CGSTHI",StringType,true),
StructField("REPCGS",StringType,true),
StructField("LIBCGS",StringType,true),
StructField("MDRSST",StringType,true),
StructField("RSSTHI",StringType,true),
StructField("REPRSS",StringType,true),
StructField("LIBRSS",StringType,true),
StructField("MDCGSS",StringType,true),
StructField("CGSTAT",StringType,true),
StructField("REPCST",StringType,true),
StructField("LIBCST",StringType,true),
StructField("MDRSSS",StringType,true),
StructField("RSSTAT",StringType,true),
StructField("REPRST",StringType,true),
StructField("LIBRST",StringType,true),
StructField("ANCIEN",DateType,true),
StructField("DATEUT",DateType,true),
StructField("ANCIE3",DateType,true),
StructField("ANCIE4",DateType,true),
StructField("ANCIE5",DateType,true),
StructField("ANCIE6",DateType,true),
StructField("ANCIE7",DateType,true),
StructField("ANCIE8",DateType,true),
StructField("ANCIE9",DateType,true),
StructField("ANCIE0",DateType,true),
StructField("LIBMAT",StringType,true),
StructField("FILLER",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX37 

                  case "ZX37" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("MODETA",StringType,true),
StructField("ETABLI",StringType,true),
StructField("REPETA",StringType,true),
StructField("LIBETA",StringType,true),
StructField("IDCONT",StringType,true),
StructField("DIRECT",StringType,true),
StructField("SERVIC",StringType,true),
StructField("SECTIO",StringType,true),
StructField("SOUSEC",StringType,true),
StructField("LEVEL5",StringType,true),
StructField("LEVEL6",StringType,true),
StructField("LEVEL7",StringType,true),
StructField("LEVEL8",StringType,true),
StructField("LEVEL9",StringType,true),
StructField("LEVELA",StringType,true),
StructField("LEVELB",StringType,true),
StructField("LEVELC",StringType,true),
StructField("FILLER",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTC1M",StringType,true),
StructField("EXTC1C",StringType,true),
StructField("EXTC1R",StringType,true),
StructField("EXTC1L",StringType,true),
StructField("EXTC2M",StringType,true),
StructField("EXTC2C",StringType,true),
StructField("EXTC2R",StringType,true),
StructField("EXTC2L",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX38 

                  case "ZX38" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("MODQUA",StringType,true),
StructField("QUALIF",StringType,true),
StructField("CLASSI",StringType,true),
StructField("REPQUA",StringType,true),
StructField("LIBQUA",StringType,true),
StructField("MODCLA",StringType,true),
StructField("REPCLA",StringType,true),
StructField("LIBCLA",StringType,true),
StructField("MODEMP",StringType,true),
StructField("REPEMP",StringType,true),
StructField("LIBEMP",StringType,true),
StructField("CODGRO",StringType,true),
StructField("MODTAR",StringType,true),
StructField("REPTAR",StringType,true),
StructField("LIBTAR",StringType,true),
StructField("MOTPRO",StringType,true),
StructField("NOORDR",StringType,true),
StructField("CODNAT",StringType,true),
StructField("MODPOS",StringType,true),
StructField("POSITI",StringType,true),
StructField("REPPOS",StringType,true),
StructField("LIBPOS",StringType,true),
StructField("MODIND",StringType,true),
StructField("INDICE",StringType,true),
StructField("REPIND",StringType,true),
StructField("LIBIND",StringType,true),
StructField("FILLE1",StringType,true),
StructField("MODCOE",StringType,true),
StructField("COEFFI",StringType,true),
StructField("REPCOE",StringType,true),
StructField("LIBCOE",StringType,true),
StructField("NIVEAU",StringType,true),
StructField("ECHELO",StringType,true),
StructField("FILLE2",StringType,true),
StructField("MODCOC",StringType,true),
StructField("COCONV",StringType,true),
StructField("REGSPE",StringType,true),
StructField("REPCOC",StringType,true),
StructField("LIBCOC",StringType,true),
StructField("FILLE3",StringType,true),
StructField("MODCIA",StringType,true),
StructField("CDCIA",StringType,true),
StructField("REPCIA",StringType,true),
StructField("LIBCIA",StringType,true),
StructField("MODPAY",StringType,true),
StructField("PAYQUA",StringType,true),
StructField("REPPAY",StringType,true),
StructField("LIBPAY",StringType,true),
StructField("MDECHL",StringType,true),
StructField("ECHLMA",StringType,true),
StructField("RPECHL",StringType,true),
StructField("LBECHL",StringType,true),
StructField("DTECHL",DateType,true),
StructField("MDECHO",StringType,true),
StructField("ECHOMA",StringType,true),
StructField("RPECHO",StringType,true),
StructField("LBECHO",StringType,true),
StructField("DTECHO",DateType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTC1M",StringType,true),
StructField("EXTC1C",StringType,true),
StructField("EXTC1R",StringType,true),
StructField("EXTC1L",StringType,true),
StructField("EXTC2M",StringType,true),
StructField("EXTC2C",StringType,true),
StructField("EXTC2R",StringType,true),
StructField("EXTC2L",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("CHBASE",StringType,true),
StructField("CHPERS",StringType,true),
StructField("CHSPEC",StringType,true),
StructField("CHNIVE",StringType,true),
StructField("CHECHL",StringType,true),
StructField("COGRPE",StringType,true),
StructField("CONIVE",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX3B 

                  case "ZX3B" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("CODCON",StringType,true),
StructField("ANNEES",DateType,true),
StructField("IDZYES",IntegerType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("DEBACQ",DateType,true),
StructField("FINACQ",DateType,true),
StructField("ACQUIA",IntegerType,true),
StructField("REPPRE",IntegerType,true),
StructField("REPECR",IntegerType,true),
StructField("REPSUI",IntegerType,true),
StructField("PAYESS",IntegerType,true),
StructField("DRTPRI",IntegerType,true),
StructField("RESTAN",IntegerType,true),
StructField("AJUST1",IntegerType,true),
StructField("MOTIF1",StringType,true),
StructField("AJUST2",IntegerType,true),
StructField("MOTIF2",StringType,true),
StructField("AJUST3",IntegerType,true),
StructField("MOTIF3",StringType,true),
StructField("AJUST4",IntegerType,true),
StructField("MOTIF4",StringType,true),
StructField("DTUPD1",DateType,true),
StructField("MOTIR1",StringType,true),
StructField("AMREP1",IntegerType,true),
StructField("CPTCR1",StringType,true),
StructField("DTUPD2",DateType,true),
StructField("MOTIR2",StringType,true),
StructField("AMREP2",IntegerType,true),
StructField("CPTCR2",StringType,true),
StructField("DTUPD3",DateType,true),
StructField("MOTIR3",StringType,true),
StructField("AMREP3",IntegerType,true),
StructField("CPTCR3",StringType,true),
StructField("AMREPT",IntegerType,true),
StructField("POSBUL",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("HHPRIS",IntegerType,true),
StructField("JJREEL",IntegerType,true),
StructField("HHREEL",IntegerType,true),
StructField("HHREST",IntegerType,true),
StructField("HHACQU",IntegerType,true),
StructField("JJRELI",IntegerType,true),
StructField("HHRELI",IntegerType,true),
StructField("JFRACT",IntegerType,true),
StructField("HFRACT",IntegerType,true),
StructField("MODELR",StringType,true),
StructField("REPELR",StringType,true),
StructField("LIBELL",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX40 

                  case "ZX40" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("DATEFF",DateType,true),
StructField("MODTRA",StringType,true),
StructField("CODTRA",StringType,true),
StructField("REPTRA",StringType,true),
StructField("LIBTRA",StringType,true),
StructField("MODINC",StringType,true),
StructField("CODINC",StringType,true),
StructField("REPINC",StringType,true),
StructField("LIBINC",StringType,true),
StructField("NBSTHD",IntegerType,true),
StructField("NBSTHW",IntegerType,true),
StructField("NBSTHM",IntegerType,true),
StructField("RTSTHR",IntegerType,true),
StructField("NBPDHD",IntegerType,true),
StructField("NBPDHW",IntegerType,true),
StructField("NBPDHM",IntegerType,true),
StructField("RTPDHR",IntegerType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTC1M",StringType,true),
StructField("EXTC1C",StringType,true),
StructField("EXTC1R",StringType,true),
StructField("EXTC1L",StringType,true),
StructField("EXTC2M",StringType,true),
StructField("EXTC2C",StringType,true),
StructField("EXTC2R",StringType,true),
StructField("EXTC2L",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("MODHOR",StringType,true),
StructField("FORANU",IntegerType,true),
StructField("FORANH",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX5V 

                  case "ZX5V" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("VALIDT",StringType,true),
StructField("TIMVAL",DateType,true),
StructField("WORKID",IntegerType,true),
StructField("SOURCE",StringType,true),
StructField("CDUSAP",StringType,true),
StructField("CDUSTO",StringType,true),
StructField("REASON",StringType,true),
StructField("WERROR",IntegerType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX6A 

                  case "ZX6A" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DEBABS",DateType,true),
StructField("IDEREM",StringType,true),
StructField("CODABS",StringType,true),
StructField("SOURCE",StringType,true),
StructField("CODLAN",StringType,true),
StructField("MODABS",StringType,true),
StructField("REPABS",StringType,true),
StructField("LIBELL",StringType,true),
StructField("FINABS",DateType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("POABBU",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX6C 

                  case "ZX6C" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUMCUM",StringType,true),
StructField("PERDEB",StringType,true),
StructField("FILLER",StringType,true),
StructField("CDAXES",StringType,true),
StructField("CODLAN",StringType,true),
StructField("MODCUM",StringType,true),
StructField("REPCUM",StringType,true),
StructField("LIBCUM",StringType,true),
StructField("MONCUM",IntegerType,true),
StructField("BPAMNT",IntegerType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX6P 

                  case "ZX6P" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("RUBPRE",StringType,true),
StructField("ORDPRE",IntegerType,true),
StructField("NUMPRE",StringType,true),
StructField("CODLAN",StringType,true),
StructField("MODPRE",StringType,true),
StructField("REPPRE",StringType,true),
StructField("LIBPRE",StringType,true),
StructField("MONPR",IntegerType,true),
StructField("MONPRD",StringType,true),
StructField("MONPRX",StringType,true),
StructField("DEBPRE",DateType,true),
StructField("FINPRE",DateType,true),
StructField("ECHPRE",IntegerType,true),
StructField("MENPR",IntegerType,true),
StructField("MENPRD",StringType,true),
StructField("MENPRX",StringType,true),
StructField("SOLPR",IntegerType,true),
StructField("SOLPRD",StringType,true),
StructField("SOLPRX",StringType,true),
StructField("UTIPRE",StringType,true),
StructField("TXIPRE",IntegerType,true),
StructField("MTINT",IntegerType,true),
StructField("MTINTD",StringType,true),
StructField("MTINTX",StringType,true),
StructField("DTCONC",DateType,true),
StructField("DTRECP",DateType,true),
StructField("DTVIRC",DateType,true),
StructField("DTPRHB",DateType,true),
StructField("CAPNA",IntegerType,true),
StructField("CAPNAD",StringType,true),
StructField("CAPNAX",StringType,true),
StructField("IMPUT",IntegerType,true),
StructField("IMPUTD",StringType,true),
StructField("IMPUTX",StringType,true),
StructField("SOLAV",IntegerType,true),
StructField("SOLAVD",StringType,true),
StructField("SOLAVX",StringType,true),
StructField("JURSID",StringType,true),
StructField("PTDAM",IntegerType,true),
StructField("PTDAMD",StringType,true),
StructField("PTDAMX",StringType,true),
StructField("WTHLPC",IntegerType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZX8K 

                  case "ZX8K" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDEREM",StringType,true),
StructField("CODRUB",StringType,true),
StructField("CODLAN",StringType,true),
StructField("CDAXES",StringType,true),
StructField("FRQVAL",StringType,true),
StructField("PERVAL",IntegerType,true),
StructField("DATRUB",DateType,true),
StructField("CODRAP",StringType,true),
StructField("SOURCE",StringType,true),
StructField("CALCUL",StringType,true),
StructField("MODELR",StringType,true),
StructField("REPELR",StringType,true),
StructField("LIBELL",StringType,true),
StructField("NBRDEC",StringType,true),
StructField("NBRBAS",IntegerType,true),
StructField("TAUSAL",IntegerType,true),
StructField("MONSAL",IntegerType,true),
StructField("TAUPAT",IntegerType,true),
StructField("MONPAT",IntegerType,true),
StructField("IMPUTA",StringType,true),
StructField("ZONEUT",StringType,true),
StructField("CODABS",StringType,true),
StructField("DEBABS",DateType,true),
StructField("FINABS",DateType,true),
StructField("IDTXTA",StringType,true),
StructField("IDTXTT",StringType,true),
StructField("TYTXPM",StringType,true),
StructField("FLTXSP",StringType,true),
StructField("IDPLAN",StringType,true),
StructField("FLTAG2",StringType,true),
StructField("MEMO01",StringType,true),
StructField("MEMO02",StringType,true),
StructField("MEMO03",StringType,true),
StructField("MEMO04",StringType,true),
StructField("MEMO05",StringType,true),
StructField("MEMO06",StringType,true),
StructField("MEMO07",StringType,true),
StructField("MEMO08",StringType,true),
StructField("MEMO09",StringType,true),
StructField("MEMO10",StringType,true),
StructField("MEMO11",StringType,true),
StructField("MODORG",StringType,true),
StructField("REPORG",StringType,true),
StructField("CODORG",StringType,true),
StructField("LIBORG",StringType,true),
StructField("QLPRWC",StringType,true),
StructField("QLPRWN",StringType,true),
StructField("QLPRW1",StringType,true),
StructField("QLPRW2",StringType,true),
StructField("QLPRW3",StringType,true),
StructField("QLPRW4",StringType,true),
StructField("QLPRW5",StringType,true),
StructField("QLPRW6",StringType,true),
StructField("QLPRW7",StringType,true),
StructField("QLPRW8",StringType,true),
StructField("TEJOU1",StringType,true),
StructField("TEJOU2",StringType,true),
StructField("TEJOU3",StringType,true),
StructField("TEJOU4",StringType,true),
StructField("TEJOU5",StringType,true),
StructField("TEJOU6",StringType,true),
StructField("TEJOU7",StringType,true),
StructField("RGPOSJ",StringType,true),
StructField("TEBULQ",StringType,true),
StructField("TEBULD",IntegerType,true),
StructField("TEBULT",StringType,true),
StructField("TEBULM",StringType,true),
StructField("RGPOSB",StringType,true),
StructField("RGPOSA",StringType,true),
StructField("RGPOSE",StringType,true),
StructField("TEMONT",StringType,true),
StructField("FLTAG1",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
StructField("CDRULE",StringType,true),
StructField("POSAGR",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZXM7 

                  case "ZXM7" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODLAN",StringType,true),
StructField("TYPCPT",StringType,true),
StructField("DATOUV",DateType,true),
StructField("DTFERM",DateType,true),
StructField("SOLCPT",IntegerType,true),
StructField("SOLCTH",IntegerType,true),
StructField("SOLCHE",IntegerType,true),
StructField("DTUTIL",DateType,true),
StructField("DTFIN",DateType,true),
StructField("MODELR",StringType,true),
StructField("REPELR",StringType,true),
StructField("LIBELL",StringType,true),
StructField("IDGPRG",IntegerType,true),
StructField("SOCCLE",StringType,true),
StructField("MATRIC",StringType,true),
StructField("NUDOSP",IntegerType,true),
StructField("IDSITU",StringType,true),
StructField("PERPAI",StringType,true),
StructField("USAGEP",StringType,true),
StructField("NUMTRT",StringType,true),
StructField("NUMBUL",StringType,true),
StructField("TIMEST",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZXMI 

                  case "ZXMI" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CDNORM",StringType,true),
StructField("CDVERS",StringType,true),
StructField("DATD0J",DateType,true),
StructField("DATF0J",DateType,true),
StructField("D05005",DateType,true),
StructField("E11001",StringType,true),
StructField("IDMDL6",StringType,true),
StructField("V00007",StringType,true),
StructField("CODLOT",StringType,true),
StructField("IDESOC",StringType,true),
StructField("IDEMAT",StringType,true),
StructField("NUGEST",IntegerType,true),
StructField("D40001",DateType,true),
StructField("X40009",StringType,true),
StructField("FLEXCL",StringType,true),
StructField("V40025",StringType,true),
StructField("FLPDEC",StringType,true),
StructField("TYPS89",StringType,true),
StructField("X40006",StringType,true),
StructField("D40010",DateType,true),
StructField("Z40018",StringType,true),
StructField("W40018",StringType,true),
StructField("V40018",StringType,true),
StructField("Z40020",StringType,true),
StructField("W40020",StringType,true),
StructField("V40020",StringType,true),
StructField("Z40026",StringType,true),
StructField("W40026",StringType,true),
StructField("V40026",StringType,true),
StructField("X40027",StringType,true),
StructField("X40028",StringType,true),
StructField("Z40029",StringType,true),
StructField("W40029",StringType,true),
StructField("V40029",StringType,true),
StructField("D40030",DateType,true),
StructField("D40031",DateType,true),
StructField("D40032",DateType,true),
StructField("X40033",StringType,true),
StructField("Z40035",StringType,true),
StructField("W40035",StringType,true),
StructField("V40035",StringType,true),
StructField("V40036",StringType,true),
StructField("V40037",StringType,true),
StructField("Z40038",StringType,true),
StructField("W40038",StringType,true),
StructField("V40038",StringType,true),
StructField("Z40039",StringType,true),
StructField("W40039",StringType,true),
StructField("V40039",StringType,true),
StructField("X40041",StringType,true),
StructField("Y40041",StringType,true),
StructField("N40043",IntegerType,true),
StructField("V40045",StringType,true),
StructField("Y40046",StringType,true),
StructField("Z30023",StringType,true),
StructField("W30023",StringType,true),
StructField("V30023",StringType,true),
StructField("X71A01",StringType,true),
StructField("X71A02",StringType,true),
StructField("X71B01",StringType,true),
StructField("X71B02",StringType,true),
StructField("X71C01",StringType,true),
StructField("X71C02",StringType,true),
StructField("N11008",IntegerType,true),
StructField("Y11001",StringType,true),
StructField("Y41012",StringType,true),
StructField("DCH012",DateType,true),
StructField("X41014",StringType,true),
StructField("DCH014",DateType,true),
StructField("D41021",DateType,true),
StructField("AAAAMM",StringType,true),
StructField("DT40FN",DateType,true),
StructField("MDRAPP",StringType,true),
StructField("BRETRO",StringType,true),
StructField("DTRAPI",DateType,true),
StructField("ZOUT01",StringType,true),
StructField("ZOUT02",StringType,true),
StructField("FILUT1",StringType,true),
StructField("FILUT2",StringType,true),
StructField("TAUDGI",IntegerType,true),
StructField("TYPDGI",StringType,true),
StructField("X50008",StringType,true),
StructField("D50010",DateType,true),
StructField("Z40066",StringType,true),
StructField("W40066",StringType,true),
StructField("V40066",StringType,true),
StructField("PERPAI",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZXMJ 

                  case "ZXMJ" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATEFF",DateType,true),
StructField("Z40002",StringType,true),
StructField("W40002",StringType,true),
StructField("V40002",StringType,true),
StructField("Z40003",StringType,true),
StructField("W40003",StringType,true),
StructField("V40003",StringType,true),
StructField("Y40004",StringType,true),
StructField("V40005",StringType,true),
StructField("Z40007",StringType,true),
StructField("W40007",StringType,true),
StructField("V40007",StringType,true),
StructField("Z40008",StringType,true),
StructField("W40008",StringType,true),
StructField("V40008",StringType,true),
StructField("V40011",StringType,true),
StructField("N40012",IntegerType,true),
StructField("N40013",IntegerType,true),
StructField("Z40014",StringType,true),
StructField("W40014",StringType,true),
StructField("V40014",StringType,true),
StructField("M40015",IntegerType,true),
StructField("V40016",StringType,true),
StructField("Z40017",StringType,true),
StructField("W40017",StringType,true),
StructField("V40017",StringType,true),
StructField("Y40019",StringType,true),
StructField("E40019",StringType,true),
StructField("Y41012",StringType,true),
StructField("E41012",StringType,true),
StructField("Z40021",StringType,true),
StructField("W40021",StringType,true),
StructField("V40021",StringType,true),
StructField("V40022",StringType,true),
StructField("Y40022",StringType,true),
StructField("N40023",IntegerType,true),
StructField("Z40024",StringType,true),
StructField("W40024",StringType,true),
StructField("V40024",StringType,true),
StructField("Y40040",StringType,true),
StructField("Z40042",StringType,true),
StructField("W40042",StringType,true),
StructField("V40042",StringType,true),
StructField("V40044",StringType,true),
StructField("IDMDL6",StringType,true),
StructField("CDINSE",StringType,true),
StructField("PERPAI",StringType,true),
StructField("N40054",IntegerType,true),
StructField("N40055",IntegerType,true),
StructField("N40059",IntegerType,true),
StructField("N40070",IntegerType,true),
StructField("N40075",IntegerType,true),
StructField("V40018",StringType,true),
StructField("V40020",StringType,true),
StructField("V40052",StringType,true),
StructField("V40053",StringType,true),
StructField("V40056",StringType,true),
StructField("V40057",StringType,true),
StructField("V40058",IntegerType,true),
StructField("V40060",StringType,true),
StructField("V40061",StringType,true),
StructField("V40062",StringType,true),
StructField("V40063",StringType,true),
StructField("V40064",StringType,true),
StructField("V40065",StringType,true),
StructField("V40066",StringType,true),
StructField("V40067",StringType,true),
StructField("V40069",StringType,true),
StructField("V40072",StringType,true),
StructField("V40073",StringType,true),
StructField("V40074",StringType,true),
StructField("V40076",StringType,true),
StructField("V40077",StringType,true),
StructField("V40078",StringType,true),
StructField("W40011",StringType,true),
StructField("W40018",StringType,true),
StructField("W40020",StringType,true),
StructField("W40053",StringType,true),
StructField("W40056",StringType,true),
StructField("W40066",StringType,true),
StructField("W40072",StringType,true),
StructField("Z40011",StringType,true),
StructField("Z40018",StringType,true),
StructField("Z40020",StringType,true),
StructField("Z40053",StringType,true),
StructField("Z40056",StringType,true),
StructField("Z40066",StringType,true),
StructField("Z40072",StringType,true),
StructField("N40068",IntegerType,true),
StructField("N40071",IntegerType,true),
StructField("V40026",StringType,true),
StructField("V40036",StringType,true),
StructField("V40037",StringType,true),
StructField("V40039",StringType,true),
StructField("W40026",StringType,true),
StructField("W40039",StringType,true),
StructField("X40070",StringType,true),
StructField("Y40041",StringType,true),
StructField("Z40026",StringType,true),
StructField("Z40039",StringType,true),
StructField("N40080",IntegerType,true),
StructField("X40071",StringType,true),
StructField("X40079",StringType,true),
StructField("X40081",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZXMM 

                  case "ZXMM" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("ORDLIG",IntegerType,true),
StructField("CPTDSN",StringType,true),
StructField("CODRUB",StringType,true),
StructField("SOURCE",StringType,true),
StructField("CATEGO",StringType,true),
StructField("TYPCOD",StringType,true),
StructField("TYPPAR",StringType,true),
StructField("MONTA1",IntegerType,true),
StructField("MONTA2",IntegerType,true),
StructField("MONTA3",IntegerType,true),
StructField("UNIMES",StringType,true),
StructField("ROLDT1",StringType,true),
StructField("DATE01",DateType,true),
StructField("ROLDT2",StringType,true),
StructField("DATE02",DateType,true),
StructField("DTDEBO",DateType,true),
StructField("DTFINO",DateType,true),
StructField("IDOPSD",StringType,true),
StructField("TYPORG",StringType,true),
StructField("V23002",StringType,true),
StructField("CDINSE",StringType,true),
StructField("TAUEFF",IntegerType,true),
StructField("CDASSI",StringType,true),
StructField("IDTRAN",StringType,true),
StructField("CODDEC",StringType,true),
StructField("PERPAI",StringType,true),
StructField("TAUXAT",IntegerType,true),
StructField("ENTAFF",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY19 

                  case "ZY19" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATAN1",DateType,true),
StructField("TYENFP",StringType,true),
StructField("DATAN2",DateType,true),
StructField("DATAN3",DateType,true),
StructField("DATAN4",DateType,true),
StructField("DATAN5",DateType,true),
StructField("DATAN6",DateType,true),
StructField("DATAN7",DateType,true),
StructField("DATAN8",DateType,true),
StructField("DATAN9",DateType,true),
StructField("DATAN0",DateType,true),
StructField("TYPTRI",StringType,true),
StructField("NOTRIE",IntegerType,true),
StructField("DTBACK",DateType,true),
StructField("DTCY01",DateType,true),
StructField("DTCY02",DateType,true),
StructField("DTRT00",DateType,true),
StructField("DTRTPR",DateType,true),
StructField("DATECP",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY1M 

                  case "ZY1M" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IMMAT",StringType,true),
StructField("IDCTRY",StringType,true),
StructField("RESTAT",StringType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("DATIMM",DateType,true),
StructField("DTBGAS",DateType,true),
StructField("PUISVH",IntegerType,true),
StructField("TYPEVH",StringType,true),
StructField("CONSTR",StringType,true),
StructField("MODELE",StringType,true),
StructField("YEMODE",DateType,true),
StructField("CYLIND",IntegerType,true),
StructField("FUELTY",StringType,true),
StructField("VALUE",IntegerType,true),
StructField("VALUED",StringType,true),
StructField("VALUEX",StringType,true),
StructField("SONDER",StringType,true),
StructField("TXYR1",IntegerType,true),
StructField("TXYR2",IntegerType,true),
StructField("TXYR3",IntegerType,true),
StructField("TXYR4",IntegerType,true),
StructField("FUELI1",IntegerType,true),
StructField("FUELI2",IntegerType,true),
StructField("FUELI3",IntegerType,true),
StructField("FUELI4",IntegerType,true),
StructField("MILE1",IntegerType,true),
StructField("MILE2",IntegerType,true),
StructField("MILE3",IntegerType,true),
StructField("MILE4",IntegerType,true),
StructField("TYVEHI",StringType,true),
StructField("CATEGO",StringType,true),
StructField("TPSATT",StringType,true),
StructField("GMSCO2",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY1S 

                  case "ZY1S" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DTEF1S",DateType,true),
StructField("STEMPL",StringType,true),
StructField("CGSTAT",StringType,true),
StructField("RSSTAT",StringType,true),
StructField("FLABGN",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY24 

                  case "ZY24" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("TRANST",StringType,true),
StructField("DATEFF",DateType,true),
StructField("ENDDAT",DateType,true),
StructField("IDCONT",StringType,true),
StructField("DISTAN",IntegerType,true),
StructField("AMOUNT",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY35 

                  case "ZY35" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DTEF00",DateType,true),
StructField("IDPS00",StringType,true),
StructField("IDJB00",StringType,true),
StructField("IDOU00",StringType,true),
StructField("RTASSI",StringType,true),
StructField("LBEMLG",StringType,true),
StructField("LBEMSH",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY38 

                  case "ZY38" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DTEF00",DateType,true),
StructField("DTEN00",DateType,true),
StructField("IDESTA",StringType,true),
StructField("FLINHE",StringType,true),
StructField("RSTRAN",StringType,true),
StructField("IDXLOC",StringType,true),
StructField("DTTRAN",DateType,true),
StructField("RSSTRE",StringType,true),
StructField("RSENDE",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY3B 

                  case "ZY3B" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDPS00",StringType,true),
StructField("IDJB00",StringType,true),
StructField("IDOU00",StringType,true),
StructField("DTEF00",DateType,true),
StructField("DTEN00",DateType,true),
StructField("DTBSUN",DateType,true),
StructField("NUMREQ",IntegerType,true),
StructField("TYASSI",StringType,true),
StructField("RTASSI",IntegerType,true),
StructField("IDCONT",StringType,true),
StructField("NBASHR",IntegerType,true),
StructField("NBFTES",IntegerType,true),
StructField("RSCHGE",StringType,true),
StructField("FLPSOW",StringType,true),
StructField("DTJBSE",DateType,true),
StructField("DTPSSE",DateType,true),
StructField("DTOUSE",DateType,true),
StructField("IDPROC",StringType,true),
StructField("IDPRCR",StringType,true),
StructField("FLAROR",StringType,true),
StructField("DTBGIN",DateType,true),
StructField("NUMARR",StringType,true),
StructField("VALIDE",StringType,true),
StructField("EMPBUD",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("TXCOMM",StringType,false),
StructField("FLBENE",StringType,true),
StructField("IDJBLG",StringType,true),
StructField("IDOULG",StringType,true),
StructField("LBJBTL",StringType,true),
StructField("FLLBJB",StringType,true),
StructField("LBJBLG",StringType,true),
StructField("IDWKGP",StringType,true),
StructField("IDEELV",StringType,true),
StructField("IDSLRG",StringType,true),
StructField("WLSLRG",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY4K 

                  case "ZY4K" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDGLCY",StringType,true),
StructField("IDPOCR",StringType,true),
StructField("IDPOCF",StringType,true),
StructField("IDGLAR",StringType,true),
StructField("IDGLAF",StringType,true),
StructField("IDSUAR",StringType,true),
StructField("IDSUAF",StringType,true),
StructField("DTEF00",DateType,true),
StructField("DTEN00",DateType,true),
StructField("IDCONT",StringType,true),
StructField("RTDIST",IntegerType,true),
StructField("FLINHE",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZY5G 

                  case "ZY5G" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("IDCONT",StringType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("CODE",StringType,true),
StructField("INDCYC",IntegerType,true),
StructField("FLTIME",StringType,true),
StructField("XIMPUT",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYAF 

                  case "ZYAF" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATAFF",DateType,true),
StructField("CDINFO",StringType,true),
StructField("TYASSI",StringType,true),
StructField("IDOU00",StringType,true),
StructField("IDPS00",StringType,true),
StructField("IDJB00",StringType,true),
StructField("TYTRST",StringType,true),
StructField("DATFIN",DateType,true),
StructField("ETABLI",StringType,true),
StructField("ETABSH",StringType,true),
StructField("ETABND",IntegerType,true),
StructField("IDCONT",StringType,true),
StructField("DIRECT",StringType,true),
StructField("SERVIC",StringType,true),
StructField("SECTIO",StringType,true),
StructField("SOUSEC",StringType,true),
StructField("LEVEL5",StringType,true),
StructField("LEVEL6",StringType,true),
StructField("LEVEL7",StringType,true),
StructField("LEVEL8",StringType,true),
StructField("LEVEL9",StringType,true),
StructField("LEVELA",StringType,true),
StructField("LEVELB",StringType,true),
StructField("LEVELC",StringType,true),
StructField("TAUAFF",IntegerType,true),
StructField("LBPSSH",StringType,true),
StructField("LBOUSH",StringType,true),
StructField("IDOS00",StringType,true),
StructField("LBOSSH",StringType,true),
StructField("MANNAM",StringType,true),
StructField("IDRG00",StringType,true),
StructField("LBRGSH",StringType,true),
StructField("IDCY00",StringType,true),
StructField("LBCYSH",StringType,true),
StructField("LBJBSH",StringType,true),
StructField("DTJBSE",DateType,true),
StructField("DTPSSE",DateType,true),
StructField("DTOUSE",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYAG 

                  case "ZYAG" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATDEB",DateType,true),
StructField("MOTIFA",StringType,true),
StructField("HRSDEB",IntegerType,true),
StructField("DATFIN",DateType,true),
StructField("HRSFIN",IntegerType,true),
StructField("TEMDEB",StringType,true),
StructField("TEMFIN",StringType,true),
StructField("GESTIO",StringType,true),
StructField("PROLON",StringType,true),
StructField("DTRECH",DateType,true),
StructField("UNITE1",IntegerType,true),
StructField("TEMTR1",StringType,true),
StructField("UNITE2",IntegerType,true),
StructField("TEMTR2",StringType,true),
StructField("ELEMAT",StringType,true),
StructField("DATUT1",DateType,true),
StructField("DATUT2",DateType,true),
StructField("SUITUT",StringType,true),
StructField("TESELE",StringType,true),
StructField("NBHEUR",IntegerType,true),
StructField("POURCE",IntegerType,true),
StructField("IDLVSR",StringType,true),
StructField("IDRTST",StringType,true),
StructField("IDRTSC",StringType,true),
StructField("IDRTSR",StringType,true),
StructField("RSABSE",StringType,true),
StructField("TYABEX",StringType,true),
StructField("NAABPD",StringType,true),
StructField("NUMARR",StringType,true),
StructField("VALIDE",StringType,true),
StructField("IDZYES",IntegerType,true),
StructField("DATUT3",DateType,true),
StructField("DATUT4",DateType,true),
StructField("DATUT5",DateType,true),
StructField("DATUT6",DateType,true),
StructField("DATUT7",DateType,true),
StructField("DATUT8",DateType,true),
StructField("DATUT9",DateType,true),
StructField("FLGUT2",StringType,true),
StructField("FLGUT3",StringType,true),
StructField("NBRUT1",IntegerType,true),
StructField("NBRUT2",IntegerType,true),
StructField("NBRUT3",IntegerType,true),
StructField("NBRUT4",IntegerType,true),
StructField("FLGINT",StringType,true),
StructField("FLGFUL",StringType,true),
StructField("DRPRAA",IntegerType,true),
StructField("DRPRMM",IntegerType,true),
StructField("DRPRJJ",IntegerType,true),
StructField("FLFINP",StringType,true),
StructField("FLIMPU",StringType,true),
StructField("FLCONG",StringType,true),
StructField("STAB00",StringType,true),
StructField("DTMEDI",DateType,true),
StructField("BLOB01",StringType,true),
StructField("NUMAR2",StringType,true),
StructField("FLAB01",StringType,true),
StructField("FLAB02",StringType,true),
StructField("FLAB03",StringType,true),
StructField("DURATN",IntegerType,true),
StructField("FLAGEB",StringType,true),
StructField("FLCONB",StringType,true),
StructField("IDEVET",StringType,true),
StructField("NATDEC",StringType,true),
StructField("VALIDD",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYAR 

                  case "ZYAR" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATCRM",DateType,true),
StructField("REFCRM",StringType,true),
StructField("DATDEB",DateType,true),
StructField("DTFNJR",DateType,true),
StructField("PASTAU",IntegerType,true),
StructField("TAUPAS",StringType,true),
StructField("TEMTAU",StringType,true),
StructField("TYPBAR",StringType,true),
StructField("TEMBCH",StringType,true),
StructField("DATDIS",DateType,true),
StructField("TEMENR",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYAU 

                  case "ZYAU" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATEFF",DateType,true),
StructField("NUMORD",IntegerType,true),
StructField("RUBAUG",StringType,true),
StructField("NBRATE",StringType,true),
StructField("IDRATE",StringType,true),
StructField("FLOVER",StringType,true),
StructField("IDCUR",StringType,true),
StructField("IDCURX",StringType,true),
StructField("DUCMQF",StringType,true),
StructField("DUPAY0",StringType,true),
StructField("MTSAL",IntegerType,true),
StructField("MTSAR",IntegerType,true),
StructField("MTSARD",StringType,true),
StructField("MTSARX",StringType,true),
StructField("DUBNQF",StringType,true),
StructField("AMBNF",IntegerType,true),
StructField("NBSTHW",IntegerType,true),
StructField("CMOTIF",StringType,true),
StructField("MTAUG",IntegerType,true),
StructField("TAUAUG",IntegerType,true),
StructField("ZONEUT",StringType,true),
StructField("VALIDE",StringType,true),
StructField("DATFIN",DateType,true),
StructField("FLPAYB",StringType,true),
StructField("AMHRL",IntegerType,true),
StructField("AMHRR",IntegerType,true),
StructField("AMHRRD",StringType,true),
StructField("AMHRRX",StringType,true),
StructField("AMPYP",IntegerType,true),
StructField("AMANN",IntegerType,true),
StructField("AMANR",IntegerType,true),
StructField("AMANRD",StringType,true),
StructField("AMANRX",StringType,true),
StructField("NUMARR",StringType,true),
StructField("TXCOMM",StringType,false),
StructField("TEMLI1",StringType,true),
StructField("MTVA1",IntegerType,true),
StructField("PBONUS",IntegerType,true),
StructField("NBPERP",IntegerType,true),
StructField("MTSAT",IntegerType,true),
StructField("MTVA2",IntegerType,true),
StructField("MTVA3",IntegerType,true),
StructField("TEMLI2",StringType,true),
StructField("TEMLI3",StringType,true),
StructField("FLGPRO",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYCA 

                  case "ZYCA" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATEFF",DateType,true),
StructField("DATFIN",DateType,true),
StructField("QUALIF",StringType,true),
StructField("CLASSI",StringType,true),
StructField("TYPPAI",StringType,true),
StructField("HORAIR",IntegerType,true),
StructField("CODGRO",StringType,true),
StructField("MOTPRO",StringType,true),
StructField("NOORDR",StringType,true),
StructField("CODNAT",StringType,true),
StructField("GRCONV",StringType,true),
StructField("POSITI",StringType,true),
StructField("INDICE",StringType,true),
StructField("FILLE1",StringType,true),
StructField("COEFFI",StringType,true),
StructField("NIVEAU",StringType,true),
StructField("ECHELO",StringType,true),
StructField("FILLE2",StringType,true),
StructField("COCONV",StringType,true),
StructField("REGSPE",StringType,true),
StructField("TYPREG",StringType,true),
StructField("FILLE3",StringType,true),
StructField("SITPRO",StringType,true),
StructField("INIDAT",DateType,true),
StructField("REDIKO",StringType,true),
StructField("FLBLOC",StringType,true),
StructField("FKCODE",StringType,true),
StructField("FKTRDE",StringType,true),
StructField("FKGRDE",StringType,true),
StructField("FKLVDE",StringType,true),
StructField("FLHVAC",StringType,true),
StructField("CDCIA",StringType,true),
StructField("PAYQUA",StringType,true),
StructField("DTALIV",DateType,true),
StructField("DTACAT",DateType,true),
StructField("ECHLMA",StringType,true),
StructField("ECHOMA",StringType,true),
StructField("DTECHL",DateType,true),
StructField("DTECHO",DateType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("CONVEN",StringType,true),
StructField("CATEGO",StringType,true),
StructField("CHBASE",StringType,true),
StructField("CHPERS",StringType,true),
StructField("CHSPEC",StringType,true),
StructField("CHNIVE",StringType,true),
StructField("CHECHL",StringType,true),
StructField("COGRPE",StringType,true),
StructField("CONIVE",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYCO 

                  case "ZYCO" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATCON",DateType,true),
StructField("DATFIN",DateType,true),
StructField("TYPCON",StringType,true),
StructField("NATCON",StringType,true),
StructField("DATPRE",DateType,true),
StructField("HORHEB",IntegerType,true),
StructField("NBHEUC",IntegerType,true),
StructField("ORGINT",StringType,true),
StructField("DURANN",IntegerType,true),
StructField("DURMOI",IntegerType,true),
StructField("DURJOU",IntegerType,true),
StructField("NBQDAY",IntegerType,true),
StructField("DEBESS",DateType,true),
StructField("FINESS",DateType,true),
StructField("NBRPRO",IntegerType,true),
StructField("NUMAVE",StringType,true),
StructField("NUMDEL",StringType,true),
StructField("DATDEL",DateType,true),
StructField("TITPOS",StringType,true),
StructField("NUMARR",StringType,true),
StructField("DTDBAP",DateType,true),
StructField("MINAPP",IntegerType,true),
StructField("MAJAPP",IntegerType,true),
StructField("FLFCNX",StringType,true),
StructField("FLECHX",StringType,true),
StructField("CATEGO",StringType,true),
StructField("MOTIFR",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
StructField("SITCON",StringType,true),
StructField("DTSGCO",DateType,true),
StructField("RSTPPL",StringType,true),
StructField("RSAVE",StringType,true),
StructField("FLAB01",StringType,true),
StructField("ZOIDCO",StringType,true),
StructField("FLIRPF",StringType,true),
StructField("NOMTUT",StringType,true),
StructField("PRETUT",StringType,true),
StructField("MOISCL",IntegerType,true),
StructField("MONTAN",IntegerType,true),
StructField("POURCE",IntegerType,true),
StructField("CONTRA",StringType,true),
StructField("CLLEVE",StringType,true),
StructField("COMENT",StringType,false),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYCS 

                  case "ZYCS" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("CODCAI",StringType,true),
StructField("REGIME",StringType,true),
StructField("DEBCAI",DateType,true),
StructField("FINCAI",DateType,true),
StructField("NUMCAI",StringType,true),
StructField("IDCONT",StringType,true),
StructField("QUOTEJ",IntegerType,true),
StructField("CONSOC",StringType,true),
StructField("CONETA",StringType,true),
StructField("NUMETA",IntegerType,true),
StructField("MOTRUP",StringType,true),
StructField("TEMCRC",StringType,true),
StructField("MOTSOR",StringType,true),
StructField("QUALIF",StringType,true),
StructField("TYPCON",StringType,true),
StructField("NATCON",StringType,true),
StructField("IDESTA",StringType,true),
StructField("IDCY00",StringType,true),
StructField("REGSPE",StringType,true),
StructField("FLMAJC",StringType,true),
StructField("AFFILI",StringType,true),
StructField("LIBPAS",StringType,true),
StructField("DATCAL",DateType,true),
StructField("NBPERS",IntegerType,true),
StructField("MATRAZ",StringType,true),
StructField("ALTASS",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYCU 

                  case "ZYCU" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("NUMCUM",StringType,true),
StructField("CDAXES",StringType,true),
StructField("IDCY00",StringType,true),
StructField("PCUMFF",StringType,true),
StructField("PCUMSS",StringType,true),
StructField("CUMANN",StringType,true),
StructField("CUMPER",StringType,true),
StructField("DATCUM",DateType,true),
StructField("MONCUM",IntegerType,true),
StructField("ZOBANA",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYDA 

                  case "ZYDA" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATABS",DateType,true),
StructField("MOTABS",StringType,true),
StructField("HRSDEB",IntegerType,true),
StructField("CDAXES",StringType,true),
StructField("NUMDRO",StringType,true),
StructField("DATDEB",DateType,true),
StructField("NUMTRA",StringType,true),
StructField("DATFIN",DateType,true),
StructField("HRSFIN",IntegerType,true),
StructField("TEMDEB",StringType,true),
StructField("TEMFIN",StringType,true),
StructField("UNITE1",IntegerType,true),
StructField("UNITE2",IntegerType,true),
StructField("NBRJOU",IntegerType,true),
StructField("SALRF",IntegerType,true),
StructField("SALRFD",StringType,true),
StructField("SALRFX",StringType,true),
StructField("TEMDEC",StringType,true),
StructField("ZONEUT",StringType,true),
StructField("DATEAG",DateType,true),
StructField("VALIDE",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYDV 

                  case "ZYDV" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODCON",StringType,true),
StructField("ANNEES",DateType,true),
StructField("IDZYES",IntegerType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("FINPRE",DateType,true),
StructField("DEBSUI",DateType,true),
StructField("DEBACQ",DateType,true),
StructField("FINACQ",DateType,true),
StructField("MVTACQ",DateType,true),
StructField("ACQUIA",IntegerType,true),
StructField("REPPRE",IntegerType,true),
StructField("REPECR",IntegerType,true),
StructField("REPSUI",IntegerType,true),
StructField("PAYESS",IntegerType,true),
StructField("DRTPRI",IntegerType,true),
StructField("PRICH1",IntegerType,true),
StructField("PRICH2",IntegerType,true),
StructField("RESTAN",IntegerType,true),
StructField("AJUST1",IntegerType,true),
StructField("MOTIF1",StringType,true),
StructField("AJUST2",IntegerType,true),
StructField("MOTIF2",StringType,true),
StructField("AJUST3",IntegerType,true),
StructField("MOTIF3",StringType,true),
StructField("AJUST4",IntegerType,true),
StructField("MOTIF4",StringType,true),
StructField("DTUPD1",DateType,true),
StructField("MOTIR1",StringType,true),
StructField("AMREP1",IntegerType,true),
StructField("CPTCR1",StringType,true),
StructField("DTUPD2",DateType,true),
StructField("MOTIR2",StringType,true),
StructField("AMREP2",IntegerType,true),
StructField("CPTCR2",StringType,true),
StructField("DTUPD3",DateType,true),
StructField("MOTIR3",StringType,true),
StructField("AMREP3",IntegerType,true),
StructField("CPTCR3",StringType,true),
StructField("AMREPT",IntegerType,true),
StructField("ACQUIR",IntegerType,true),
StructField("MOTACB",StringType,true),
StructField("ACQUIB",IntegerType,true),
StructField("MOTACC",StringType,true),
StructField("ACQUIC",IntegerType,true),
StructField("AJUACQ",IntegerType,true),
StructField("BA10SA",IntegerType,true),
StructField("BA10SO",IntegerType,true),
StructField("DATTIM",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYE4 

                  case "ZYE4" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("TYPCPT",StringType,true),
StructField("DTOUV",DateType,true),
StructField("DTFERM",DateType,true),
StructField("SOLCPT",IntegerType,true),
StructField("SOLCTH",IntegerType,true),
StructField("SOLCHE",IntegerType,true),
StructField("DTUTIL",DateType,true),
StructField("DTFIN",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYE6 

                  case "ZYE6" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DTOPER",DateType,true),
StructField("TYPOPE",StringType,true),
StructField("NUMORD",IntegerType,true),
StructField("TYPCPT",StringType,true),
StructField("NBJOUR",IntegerType,true),
StructField("NBJOTH",IntegerType,true),
StructField("NBJOUV",IntegerType,true),
StructField("NBHEUR",IntegerType,true),
StructField("AMNUM",IntegerType,true),
StructField("AMNUMD",StringType,true),
StructField("AMNUMX",StringType,true),
StructField("SOLCHE",IntegerType,true),
StructField("CDORIG",StringType,true),
StructField("TEXTE1",StringType,true),
StructField("TEXTE2",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYEL 

                  case "ZYEL" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("CODFIX",StringType,true),
StructField("CDAXES",StringType,true),
StructField("DEBFIX",DateType,true),
StructField("FINFIX",DateType,true),
StructField("SUBSTI",StringType,true),
StructField("CFORMA",StringType,true),
StructField("TEMNBR",StringType,true),
StructField("NBRBAS",IntegerType,true),
StructField("CODNBR",StringType,true),
StructField("TEMSAL",StringType,true),
StructField("SALFIX",IntegerType,true),
StructField("CODSAL",StringType,true),
StructField("TEMPAT",StringType,true),
StructField("PATFIX",IntegerType,true),
StructField("CODPAT",StringType,true),
StructField("TESELE",StringType,true),
StructField("NBORDE",IntegerType,true),
StructField("FLTXSP",StringType,true),
StructField("IDREC1",StringType,true),
StructField("IDREC2",StringType,true),
StructField("IDREC3",StringType,true),
StructField("IDREC4",StringType,true),
StructField("IDREC5",StringType,true),
StructField("IMPUTA",StringType,true),
StructField("MEMO01",StringType,true),
StructField("MEMO02",StringType,true),
StructField("MEMO03",StringType,true),
StructField("MEMO04",StringType,true),
StructField("MEMO05",StringType,true),
StructField("MEMO06",StringType,true),
StructField("MEMO07",StringType,true),
StructField("MEMO08",StringType,true),
StructField("MEMO09",StringType,true),
StructField("MEMO10",StringType,true),
StructField("MEMO11",StringType,true),
StructField("ZOBANA",StringType,true),
StructField("ROLDT1",StringType,true),
StructField("DATE01",DateType,true),
StructField("ROLDT2",StringType,true),
StructField("DATE02",DateType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYES 

                  case "ZYES" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATENT",DateType,true),
StructField("CODENT",StringType,true),
StructField("IDZYES",IntegerType,true),
StructField("DATSOR",DateType,true),
StructField("CODSOR",StringType,true),
StructField("PHYSOR",DateType,true),
StructField("DTPAYT",DateType,true),
StructField("TESOLD",StringType,true),
StructField("FLREHR",StringType,true),
StructField("FLPROP",StringType,true),
StructField("IDCY00",StringType,true),
StructField("CGSTAT",StringType,true),
StructField("RSSTAT",StringType,true),
StructField("FLCHHD",StringType,true),
StructField("RSTRAN",StringType,true),
StructField("IDXCOM",StringType,true),
StructField("IDTRAN",StringType,true),
StructField("CGSTHI",StringType,true),
StructField("RSSTHI",StringType,true),
StructField("DTBGPR",DateType,true),
StructField("NUMARR",StringType,true),
StructField("VALIDE",StringType,true),
StructField("DTHCHL",DateType,true),
StructField("DTMCHL",DateType,true),
StructField("NEXEMP",StringType,true),
StructField("DTBENE",DateType,true),
StructField("FLSPCL",StringType,true),
StructField("FLTRAN",StringType,true),
StructField("BLOB01",StringType,true),
StructField("FLNC00",StringType,true),
StructField("DTPRFR",DateType,true),
StructField("BGDPFR",DateType,true),
StructField("ENDPFR",DateType,true),
StructField("BGNPFR",DateType,true),
StructField("ENNPFR",DateType,true),
StructField("BGNNFR",DateType,true),
StructField("ENNNFR",DateType,true),
StructField("TEMSUI",StringType,true),
StructField("NUMORD",IntegerType,true),
StructField("NUMSUB",IntegerType,true),
StructField("TYPDEC",StringType,true),
StructField("PERDEB",StringType,true),
StructField("PERFIN",StringType,true),
StructField("TEMSEL",StringType,true),
StructField("USERSB",StringType,true),
StructField("RSSTDE",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYHB 

                  case "ZYHB" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATDEB",DateType,true),
StructField("DTDECI",DateType,true),
StructField("DATFIN",DateType,true),
StructField("FLDUR1",StringType,true),
StructField("FLCHAU",StringType,true),
StructField("FLCOTO",StringType,true),
StructField("FLPLAN",IntegerType,true),
StructField("FLEA00",IntegerType,true),
StructField("FLIMPR",IntegerType,true),
StructField("FLESTA",IntegerType,true),
StructField("FLCDTD",IntegerType,true),
StructField("FLCFP0",IntegerType,true),
StructField("FLVGNM",IntegerType,true),
StructField("FLVEGM",IntegerType,true),
StructField("FLORPG",IntegerType,true),
StructField("FLFEII",IntegerType,true),
StructField("FLRENS",IntegerType,true),
StructField("FLACCI",IntegerType,true),
StructField("FLINVP",IntegerType,true),
StructField("FLSAPO",IntegerType,true),
StructField("FLASMU",IntegerType,true),
StructField("TEMAVI",IntegerType,true),
StructField("FLMUTG",IntegerType,true),
StructField("FLPENM",IntegerType,true),
StructField("FLALLO",IntegerType,true),
StructField("TEMCAR",IntegerType,true),
StructField("TEMBEN",IntegerType,true),
StructField("TEMHAN",IntegerType,true),
StructField("FLHPLD",StringType,true),
StructField("POUHAN",IntegerType,true),
StructField("DATPEN",DateType,true),
StructField("CATPEN",StringType,true),
StructField("TXINCA",IntegerType,true),
StructField("TEMHAT",IntegerType,true),
StructField("FL5212",IntegerType,true),
StructField("IDMCAT",StringType,true),
StructField("FLMADE",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYPR 

                  case "ZYPR" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("RUBPRE",StringType,true),
StructField("ORDPRE",IntegerType,true),
StructField("NUMPRE",StringType,true),
StructField("PYDSTP",StringType,true),
StructField("MONPR",IntegerType,true),
StructField("MONPRD",StringType,true),
StructField("MONPRX",StringType,true),
StructField("PTDAM",IntegerType,true),
StructField("PTDAMD",StringType,true),
StructField("PTDAMX",StringType,true),
StructField("DEBPRE",DateType,true),
StructField("FINPRE",DateType,true),
StructField("FILSTA",IntegerType,true),
StructField("NBEXMP",IntegerType,true),
StructField("ADDSDE",IntegerType,true),
StructField("HEADFA",StringType,true),
StructField("NBDEPN",IntegerType,true),
StructField("NBDPCH",IntegerType,true),
StructField("VOCATI",IntegerType,true),
StructField("DTRECP",DateType,true),
StructField("CONSEN",StringType,true),
StructField("TYDEBT",IntegerType,true),
StructField("WTHLPC",IntegerType,true),
StructField("DELINQ",StringType,true),
StructField("SECFAM",StringType,true),
StructField("JURSID",StringType,true),
StructField("ECHPRE",IntegerType,true),
StructField("MENPR",IntegerType,true),
StructField("MENPRD",StringType,true),
StructField("MENPRX",StringType,true),
StructField("SOLPR",IntegerType,true),
StructField("SOLPRD",StringType,true),
StructField("SOLPRX",StringType,true),
StructField("UTIPRE",StringType,true),
StructField("TXINTE",IntegerType,true),
StructField("MTINT",IntegerType,true),
StructField("MTINTD",StringType,true),
StructField("MTINTX",StringType,true),
StructField("DTCONC",DateType,true),
StructField("DTVIRC",DateType,true),
StructField("CAPNA",IntegerType,true),
StructField("CAPNAD",StringType,true),
StructField("CAPNAX",StringType,true),
StructField("IMPUT",IntegerType,true),
StructField("IMPUTD",StringType,true),
StructField("IMPUTX",StringType,true),
StructField("NUMARR",StringType,true),
StructField("NUMWOM",IntegerType,true),
StructField("HEALTH",DateType,true),
StructField("AGREDT",DateType,true),
StructField("FINORG",DateType,true),
StructField("FLLSUM",StringType,true),
StructField("FLTOTS",StringType,true),
StructField("ZOBANA",StringType,true),
StructField("CDRULE",StringType,true),
StructField("AMOVP",IntegerType,true),
StructField("AMOVPD",StringType,true),
StructField("AMOVPX",StringType,true),
StructField("PERPAI",StringType,true),
StructField("FLOVPA",StringType,true),
StructField("PRENUM",StringType,true),
StructField("MTHMX",IntegerType,true),
StructField("MTHMXD",StringType,true),
StructField("MTHMXX",StringType,true),
StructField("IDPAYE",StringType,true),
StructField("NMPAY2",StringType,true),
StructField("NATPRE",StringType,true),
StructField("OBJPRE",StringType,true),
StructField("ORGPRE",StringType,true),
StructField("REFPRE",StringType,true),
StructField("MONEP",IntegerType,true),
StructField("MONEPD",StringType,true),
StructField("MONEPX",StringType,true),
StructField("DATPRE",DateType,true),
StructField("RTASSU",IntegerType,true),
StructField("AMASS",IntegerType,true),
StructField("AMASSD",StringType,true),
StructField("AMASSX",StringType,true),
StructField("FLHYPO",StringType,true),
StructField("REFHYP",StringType,true),
StructField("AMPEC",IntegerType,true),
StructField("AMPECD",StringType,true),
StructField("AMPECX",StringType,true),
StructField("AMDEC",IntegerType,true),
StructField("AMDECD",StringType,true),
StructField("AMDECX",StringType,true),
StructField("REGIME",StringType,true),
StructField("FLDIGR",StringType,true),
StructField("AMDIG",IntegerType,true),
StructField("AMDIGD",StringType,true),
StructField("AMDIGX",StringType,true),
StructField("ETAPRE",StringType,true),
StructField("FRPAIE",StringType,true),
StructField("PERGRA",IntegerType,true),
StructField("COMCLO",StringType,true),
StructField("NBEASS",IntegerType,true),
StructField("MODASS",StringType,true),
StructField("FLDBON",StringType,true),
StructField("MODBON",StringType,true),
StructField("RTBON",IntegerType,true),
StructField("AMBON",IntegerType,true),
StructField("AMBOND",StringType,true),
StructField("AMBONX",StringType,true),
StructField("FLGNTA",StringType,true),
StructField("STVALI",StringType,true),
StructField("MOTREG",StringType,true),
StructField("NBRRMB",IntegerType,true),
StructField("AMTR1",IntegerType,true),
StructField("AMTR1D",StringType,true),
StructField("AMTR1X",StringType,true),
StructField("RTTR1",IntegerType,true),
StructField("AMET1",IntegerType,true),
StructField("AMET1D",StringType,true),
StructField("AMET1X",StringType,true),
StructField("AME1G",IntegerType,true),
StructField("AME1GD",StringType,true),
StructField("AME1GX",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYRG 

                  case "ZYRG" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("NUDOSP",IntegerType,true),
StructField("RUBREG",StringType,true),
StructField("MONT1",IntegerType,true),
StructField("MONT1D",StringType,true),
StructField("MONT1X",StringType,true),
StructField("MONT2",IntegerType,true),
StructField("MONT2D",StringType,true),
StructField("MONT2X",StringType,true),
StructField("MONT3",IntegerType,true),
StructField("MONT3D",StringType,true),
StructField("MONT3X",StringType,true),
StructField("MONT4",IntegerType,true),
StructField("MONT4D",StringType,true),
StructField("MONT4X",StringType,true),
StructField("MONT5",IntegerType,true),
StructField("MONT5D",StringType,true),
StructField("MONT5X",StringType,true),
StructField("RESUL",IntegerType,true),
StructField("RESULD",StringType,true),
StructField("RESULX",StringType,true),
StructField("IDCY00",StringType,true),
StructField("ZOBANA",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYTL 

                  case "ZYTL" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATEFF",DateType,true),
StructField("CODTRA",StringType,true),
StructField("NBSTHD",IntegerType,true),
StructField("NBSTHW",IntegerType,true),
StructField("NBSTHM",IntegerType,true),
StructField("NBSTHP",IntegerType,true),
StructField("RTSTHR",IntegerType,true),
StructField("NBPDHD",IntegerType,true),
StructField("NBPDHW",IntegerType,true),
StructField("NBPDHM",IntegerType,true),
StructField("NBPDHP",IntegerType,true),
StructField("RTPDHR",IntegerType,true),
StructField("FORANU",IntegerType,true),
StructField("FORANH",IntegerType,true),
StructField("MODHOR",StringType,true),
StructField("CODINC",StringType,true),
StructField("NUMARR",StringType,true),
StructField("SURCOT",StringType,true),
StructField("VALIDE",StringType,true),
StructField("FINPRE",DateType,true),
StructField("DURANN",IntegerType,true),
StructField("DURMOI",IntegerType,true),
StructField("DURJOU",IntegerType,true),
StructField("FLWKFO",StringType,true),
StructField("RSFO00",StringType,true),
StructField("QTRT00",IntegerType,true),
StructField("OPTCDA",StringType,true),
StructField("FLTLRE",StringType,true),
StructField("EXTDA1",DateType,true),
StructField("EXTDA2",DateType,true),
StructField("EXTCF1",StringType,true),
StructField("EXTCF2",StringType,true),
StructField("EXTC21",StringType,true),
StructField("EXTC22",StringType,true),
StructField("EXTCO1",StringType,true),
StructField("EXTCO2",StringType,true),
StructField("EXTNU1",IntegerType,true),
StructField("EXTNU2",IntegerType,true),
StructField("EXT100",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYWB 

                  case "ZYWB" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("DATXXX",DateType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATNOT",DateType,true),
StructField("PREEFF",StringType,true),
StructField("DADEB1",DateType,true),
StructField("DAFIN1",DateType,true),
StructField("PREPAY",StringType,true),
StructField("DADEB2",DateType,true),
StructField("DAFIN2",DateType,true),
StructField("DAPHYS",DateType,true),
StructField("PRENPA",StringType,true),
StructField("DADEB3",DateType,true),
StructField("DAFIN3",DateType,true),
StructField("PRENEF",StringType,true),
StructField("MOTIFS",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYWV 

                  case "ZYWV" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("TYPDET",StringType,true),
StructField("PAYDET",StringType,true),
StructField("SITFAM",StringType,true),
StructField("RESFIS",StringType,true),
StructField("NUMORD",StringType,true),
StructField("COMMEN",StringType,true),
 
                  StructField("filepath",StringType,false)
    ))
 
//------------ZYWW 

                  case "ZYWW" => 
 
                  StructType( List( 
 
                  StructField("NUDOSS",IntegerType,true),
StructField("NULIGN",IntegerType,true),
StructField("NULIGS",IntegerType,true),
StructField("NULIGP",IntegerType,true),
StructField("TEACTI",StringType,true),
StructField("SOCDOS",StringType,true),
StructField("PGPDOS",IntegerType,true),
StructField("CODREG",StringType,true),
StructField("DATDEB",DateType,true),
StructField("DATFIN",DateType,true),
StructField("REPART",IntegerType,true),
 
                  StructField("filepath",StringType,false)
    ))
 


  

  case default => null
  }
  
   return struct
}